#
# These variables are common to the project, independent of
# the environment (development, staging, production, ...)
#

# Default to ansible_python, probably /usr/bin/python3
#python_version : "3.9"

# This is automacally found, but can be explicetely set
django_repo    : ""

# Extra path to load Python modules
pythonpath  : "apps"

# Extra services
django_with_node: false
